### ISSUE TITLE
FOSS git GUI

### ISSUE THREAD

**Issue by falkmielke** [inbo/git-course#67]
I would like to pull up discussion about the choice of a git GUI.
This course relies on the use of [github desktop](https://desktop.github.com). However, 
- that tool is **not open source**. 
- It also shows suspicious behavior (immediate installation on windows without user options such as path)*. 
- Finally, an ssh-key based auth seems dysfunctional, so I could not even use it on windows.

I have tested two FOSS alternatives, both seem fine:
- `git cola`: https://git-cola.github.io
- `sourcegit`: https://github.com/sourcegit-scm/sourcegit

Both are FOSS, install in user space, have intuitive design much resembling github desktop and seem to bring all the functionality needed. The tools seem fully interchangeable.

I would anticipate that a switch would be feasible without much effort, except for a prior test by the workshop host. 
Yet there is also no urgent need (just well-intended idealism), so feel free to choose to neglect this issue.

* ... though, admittedly, I am glad that it does so in "user space" (i.e. without admin rights).

**Comment by peterdesmet** [comment]
Thanks, that is valid feedback. At INBO, we occasionally give the GitHub workshop, but only the [afternoon session](https://github.com/inbo/git-course?tab=readme-ov-file#afternoon-session). There we indeed recommend R Studio and GitHub Desktop (since that is where we collectively have the most experience). It is a good idea to recommend open source alternatives.
